---
# Implement your Pre Workload deployment tasks here

- name: usercount debug
  debug:
    msg: "Debugging num_users {{ num_users }}"

# Figure out paths
- name: extract api_url
  command: oc whoami --show-server
  register: api_url_r

- name: set the master
  set_fact:
    master_url: "{{ api_url_r.stdout | trim }}"

- debug: var=master_url

- name: extract console_url
  command: oc whoami --show-server
  register: console_url_r

- name: set the console
  set_fact:
    console_url: "{{ console_url_r.stdout | trim }}"

- name: debug values
  debug:
    msg:
    - "master URL: {{ master_url }}"
    - "console URL: {{ console_url }}"
    - "route subdomain: {{ route_subdomain }}"
    - "ocp_username: {{ ocp_username }}"

# Leave this as the last task in the playbook.
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."
  when: not silent|bool
