---
# Implement your Workload removal tasks here

- name: Transfer executable script script
  copy:
    src=../files/resetlab_ccn.sh dest=/tmp/resetlab_ccn.sh mode=0777

- name: Execute the resetlab_ccn.sh
  shell: /tmp/resetlab_ccn.sh -c {{ num_users }} -m {{ module_type }}

- name: Remove the resetlab_ccn.sh
  file: path=/tmp/resetlab_ccn.sh state=absent

- name: Check codeready installed
  shell: command -v crwctl >/dev/null 2>&1
  register: result
  ignore_errors: yes

- name: Remove codeready template symlink
  file: path=/bin/custom-resource.yaml state=absent
  become: true
  when: "{{ result.rc }} == 0"

- name: Remove codeready binary symlink
  file: path=/usr/bin/crwctl state=absent
  become: true
  when: "{{ result.rc }} == 0"

- name: Remove codeready operator
  file: path=/opt/crwctl state=absent
  become: true
  when: "{{ result.rc }} == 0"

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
