---
# Implement your Workload deployment tasks here

- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

- name: Setting up num_users for workshop
  debug:
    msg: "Setting up num_users for workshop num_users = {{ num_users }}"

- name: Setting up module_type for workshop
  debug:
    msg: "Setting up module_type for workshop module_type = {{ module_type }}"

- name: Check codeready installed
  shell: command -v crwctl >/dev/null 2>&1
  register: result
  ignore_errors: yes

- name: Transfer codeready archive
  copy:
    src=../files/codeready-workspaces-operator-installer.tar.gz dest=/tmp/codeready.tar.gz
  when: "{{ result.rc }} != 0"

- name: Install codeready operator
  shell: tar -zxvf /tmp/codeready.tar.gz -C /opt/
  become: true
  when: "{{ result.rc }} != 0"

- name: Remove codeready archive
  file: path=/tmp/codeready.tar.gz state=absent
  when: "{{ result.rc }} != 0"

- name: Symlink codeready binary
  shell: ln -s /opt/crwctl/deploy.sh /usr/bin/crwctl
  become: true
  when: "{{ result.rc }} != 0"

- name: Symlink codeready template
  shell: ln -s /opt/crwctl/custom-resource.yaml /bin/custom-resource.yaml
  become: true
  when: "{{ result.rc }} != 0"

- name: Transfer executable script script
  copy:
    src=../files/preparelab_ccn.sh dest=/tmp/preparelab_ccn.sh mode=0777

- name: Execute the preparelab_ccn.sh
  shell: /tmp/preparelab_ccn.sh -c {{ num_users }} -m {{ module_type }} -p {{ workshop_openshift_user_password }}

- name: Remove the preparelab_ccn.sh
  file: path=/tmp/preparelab_ccn.sh state=absent

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
